name: Download Offline Windows Wheels

on:
  workflow_dispatch:

jobs:
  download-wheels:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Download Wheels
      run: |
        mkdir wheels
        pip download pywebview websockets pyinstaller -d ./wheels

    - name: Upload Wheels Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-pip-wheels
        path: wheels/*